name: koa
description: 基于Dart实现的后端框架
version: 0.0.1
author: allan <1440806569@qq.com>
homepage: https://github.com/dart-koa/koa
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  mime: ^0.9.6+3
  http_server: ^0.9.8+3
